// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFI4wr1MQmZmaur_-koA2VssqURMbSyU',
    appId: '1:745691231150:web:b6c385bd81a611a63a4e3f',
    messagingSenderId: '745691231150',
    projectId: 'chatappgroup5',
    authDomain: 'chatappgroup5.firebaseapp.com',
    storageBucket: 'chatappgroup5.appspot.com',
    measurementId: 'G-2087CG64DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMI3fYhenRyyq7jNniY4n4tlqfhmNmuNk',
    appId: '1:745691231150:android:6d0fcdadf866d88d3a4e3f',
    messagingSenderId: '745691231150',
    projectId: 'chatappgroup5',
    storageBucket: 'chatappgroup5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3HwfwSUov1Xv0QjVcpVC8kK0qnpNVho',
    appId: '1:745691231150:ios:7e3bcfc934ed68fb3a4e3f',
    messagingSenderId: '745691231150',
    projectId: 'chatappgroup5',
    storageBucket: 'chatappgroup5.appspot.com',
    iosBundleId: 'com.example.mobileAppGroup5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3HwfwSUov1Xv0QjVcpVC8kK0qnpNVho',
    appId: '1:745691231150:ios:7e3bcfc934ed68fb3a4e3f',
    messagingSenderId: '745691231150',
    projectId: 'chatappgroup5',
    storageBucket: 'chatappgroup5.appspot.com',
    iosBundleId: 'com.example.mobileAppGroup5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGFI4wr1MQmZmaur_-koA2VssqURMbSyU',
    appId: '1:745691231150:web:5795a6e892ea0d543a4e3f',
    messagingSenderId: '745691231150',
    projectId: 'chatappgroup5',
    authDomain: 'chatappgroup5.firebaseapp.com',
    storageBucket: 'chatappgroup5.appspot.com',
    measurementId: 'G-188F2RR53Y',
  );

}